language: elixir
elixir:
  - 1.2.0
sudo: false
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - eric.meadows.jonsson@gmail.com
otp_release:
  - 18.1
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
