language: elixir
sudo: false # to use faster container based build environment
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
otp_release:
  - 17.0
  - 17.1
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
